[ir:simulation]
SHOULD_LINEMERGE = false
TIME_PREFIX = ^
TIME_FORMAT = %Y-%m-%dT%H:%M:%S%z
MAX_TIMESTAMP_LOOKAHEAD = 32
TRUNCATE = 0

[linux:audit]
SHOULD_LINEMERGE = false
TRUNCATE = 0

[linux:auth]
SHOULD_LINEMERGE = false
TRUNCATE = 0
